GET http://localhost:5127/games

###
GET http://localhost:5127/genres

###
POST http://localhost:5127/games
Content-Type: application/json

{
  "name": "The Legend of Zelda: Breath of the Wild",
  "genreid": 1,
  "price": 59.99,
  "releaseDate": "2017-03-03"
}
###
POST http://localhost:5127/genres
Content-Type: application/json

{
  "name": "Action"
}

###
PUT http://localhost:5127/games/1
Content-Type: application/json

{
    "name": "The Legend of Zelda: Breath of the Wild",
    "genreid": 2,
    "price": 59.99,
    "releaseDate": "2017-03-03"
}

###
###
PUT http://localhost:5127/genres/1
Content-Type: application/json

{
    "name": "Drama"
}